#!/usr/bin/env bash
# installs nginx
# configure it to listen on port 80
# print "Hello World"

sudo apt update
sudo apt -y install nginx
sudo ufw allow 'Nginx HTTP'
echo 'Hello World!' | sudo tee /var/www/html/index.html > /dev/null
sudo service nginx start
