#!/usr/bin/env bash
# pings an IP address passed as an argument, 5 times
# -lte checks if the total number of argument is less than or equal to 1

if [[ $# -lt 1 ]]; then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
	ping -c 5 "$1"
fi
