#!/usr/bin/env bash
# Displays a list of currently running processes.
# Shows all processes, for all users, including those which might not have a TTY.
# It displays in a user-oriented format and shows process hierarchy.
ps -auxf
